---
- name: 'install k8s-cluster hostname'
  hosts: external
  become: true
  tasks:
    - name: "Add nodes /etc/hosts"
      lineinfile:
        name: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "192.168.10.12 k8s-node1"
        - "192.168.10.30 k8s-node2"
        - "192.168.10.26 k8s-node3"
